import Image from "next/image";
import Link from "next/link";
import logo from "../../../../../marca/MokiLogo2-transparente.png";
import { AgentDemo } from "../molecules/agent-demo";
import "../../landing.css";

const steps = [
  ["01", "Empieza con una idea.", "Ese documento por resumir. Un tema por explorar. Una respuesta que preparas una y otra vez.", "¿Y si esto lo hiciera un agente?"],
  ["02", "Dale forma, paso a paso.", "Conecta bloques para leer, pensar y escribir. Tú decides las instrucciones y el orden.", "Tu proceso. Tus reglas."],
  ["03", "Pruébalo. Hazlo tuyo.", "Revisa la respuesta, ajusta lo que necesites y vuelve a probar. Tu agente también puede evolucionar.", "Cada intento, una mejor versión."],
];
export function Landing() {
  return <main className="landing">
    <a className="landing-skip" href="#contenido">Ir al contenido</a>
    <header className="landing-header"><Link href="/" className="landing-logo" aria-label="Moki, inicio"><Image src={logo} alt="Moki by Dekids" priority sizes="130px" /></Link><nav aria-label="Navegación principal"><a className="landing-nav-section" href="#como-funciona">Cómo funciona</a><a className="landing-nav-section" href="#en-accion">En acción</a><Link className="landing-login" href="/login">Iniciar sesión</Link><Link className="landing-nav-cta" href="/registro">Empieza a crear <span aria-hidden="true">↗</span></Link></nav></header>
    <section className="landing-hero" id="contenido"><div className="landing-hero-topline"><span className="landing-pill"><i /> GRANDES IDEAS. PASOS SIMPLES.</span><span className="landing-edition">HECHO PARA TU PRÓXIMA IDEA ↙</span></div><div className="landing-hero-grid"><h1>Tu forma de trabajar.<br /><span>En modo <em>agente.</em><svg viewBox="0 0 440 22" aria-hidden="true"><path d="M4 16C112 1 269 0 434 9M75 20C195 7 325 8 395 13" /></svg></span></h1><div className="landing-hero-aside"><p>Convierte lo que haces en un agente de IA. Conecta pasos, prueba tus ideas y deja que tomen forma.</p><p className="landing-hero-note">En español. Sin escribir código. A tu manera.</p><a href="#en-accion" className="landing-text-link">Descubre lo que puedes crear <span aria-hidden="true">↓</span></a></div></div><div className="landing-actions"><Link className="landing-primary" href="/registro">Crear mi primer agente <span aria-hidden="true">↗</span></Link><a className="landing-secondary" href="#en-accion"><span className="landing-play" aria-hidden="true">▶</span> Ver a Moki en acción</a><span className="landing-hero-caption">Una idea es todo lo que necesitas.</span></div></section>
    <AgentDemo />
    <div className="landing-principles" aria-label="Características de Moki"><span><b aria-hidden="true">◇</b> Construcción visual</span><span><b aria-hidden="true">↗</b> Ideas que puedes probar</span><span><b aria-hidden="true">◎</b> Siempre en español</span><span><b aria-hidden="true">⌘</b> Sin escribir código</span></div>
    <section className="landing-how" id="como-funciona" aria-labelledby="landing-how-title"><div className="landing-section-heading"><div><p className="landing-eyebrow">DE «¿Y SI…?» A «YA ESTÁ»</p><h2 id="landing-how-title">Lo complejo se vuelve<br /><span>un paso a la vez.</span></h2></div><p>No necesitas saber programar.<br />Solo saber qué quieres resolver.</p></div><ol className="landing-steps">{steps.map(([number, title, text, detail]) => <li key={number}><div className="landing-step-number">{number}<span aria-hidden="true">↗</span></div><h3>{title}</h3><p>{text}</p><span className="landing-step-detail">{detail}</span></li>)}</ol></section>
    <section className="landing-remix"><div className="landing-remix-art" aria-hidden="true"><div className="landing-mini-agent mini-back"><span>✳</span><b>Una buena idea</b><small>El punto de partida</small></div><div className="landing-mini-agent mini-front"><span>↗</span><b>Tu propia versión</b><small>Adaptada a tu manera</small><div className="landing-mini-blocks"><i /><i /><i /></div></div><span className="landing-art-caption">CREAR · ADAPTAR · COMPARTIR</span></div><div className="landing-remix-copy"><p className="landing-eyebrow">LAS IDEAS SE CONSTRUYEN JUNTAS</p><h2>No siempre tienes<br />que empezar de cero.</h2><p>Explora agentes en el Marketplace, crea una copia editable y dale tu toque. Una idea de alguien más puede ser el inicio de tu siguiente gran idea.</p><Link className="landing-text-link" href="/registro">Empieza a explorar con tu cuenta <span aria-hidden="true">↗</span></Link></div></section>
    <section className="landing-closing"><p className="landing-eyebrow">MENOS «ALGÚN DÍA». MÁS «VAMOS A HACERLO».</p><h2>Tu próxima gran idea<br />empieza con <span>un paso.<svg viewBox="0 0 440 22" aria-hidden="true"><path d="M4 16C112 1 269 0 434 9" /></svg></span></h2><Link className="landing-primary" href="/registro">Crear mi primer agente <span aria-hidden="true">↗</span></Link><p>Haz espacio para lo que puedes imaginar.</p><span className="landing-closing-star" aria-hidden="true">✳</span></section>
    <footer className="landing-footer"><Link href="/" className="landing-logo" aria-label="Moki, inicio"><Image src={logo} alt="Moki by Dekids" sizes="130px" /></Link><p>Una idea. Un paso a la vez.</p><a href="#contenido">Volver arriba <span aria-hidden="true">↑</span></a></footer>
  </main>;
}
