"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { currentUser } from "../../../../shared/services/auth.ts";
import { runSavedAgent, type SearchSource } from "../../../../shared/services/agent-run.ts";
import type { MarketplaceAgent } from "../../../../app/api/marketplace/shared.ts";
import { forkMarketplaceAgent, getMarketplaceAgent } from "../../services/marketplace.ts";
import "../../marketplace.css";

export function MarketplaceDetail({ agentId }: { agentId: string }) {
  const [agent, setAgent] = useState<MarketplaceAgent | null>(null); const [ownerId, setOwnerId] = useState<string | null>(null); const [input, setInput] = useState(""); const [documents, setDocuments] = useState<Map<string, File>>(new Map()); const [output, setOutput] = useState(""); const [sources, setSources] = useState<SearchSource[]>([]); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; void Promise.all([getMarketplaceAgent(agentId), currentUser()]).then(([value, user]) => { if (active) { setAgent(value); setOwnerId(user?.id ?? null); } }).catch((reason) => { if (active) setNotice(reason instanceof Error ? reason.message : "No pudimos cargar este agente."); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, [agentId]);
  function document(stepId: string, file: File | null) { setDocuments((current) => { const next = new Map(current); if (file) next.set(stepId, file); else next.delete(stepId); return next; }); }
  async function run() { if (!agent || busy) return; const missing = agent.steps.find((step) => step.blockType === "leer-documento" && !documents.has(step.id)); if (missing) { setNotice(`Carga un documento para el bloque ${agent.steps.indexOf(missing) + 1}.`); return; } setBusy(true); setNotice(""); setOutput(""); setSources([]); try { const result = await runSavedAgent(agent.id, input.trim() || "Caso de prueba de ejemplo", documents); setOutput(result.output ?? "La ejecución no produjo una respuesta."); setSources(result.sources); } catch (error) { setNotice(error instanceof Error ? error.message : "No pudimos ejecutar este agente."); } finally { setBusy(false); } }
  async function fork() { if (!agent || busy) return; setBusy(true); setNotice(""); try { await forkMarketplaceAgent(agent.id); setNotice("Fork creado en Mis agentes. Ábrelo desde el Constructor para editarlo."); } catch (error) { setNotice(error instanceof Error ? error.message : "No pudimos crear el fork."); } finally { setBusy(false); } }
  if (!agent) return <main className="marketplace"><Link href="/marketplace">← Marketplace</Link><p role="status">{notice || "Cargando agente…"}</p></main>;
  const own = agent.ownerId === ownerId;
  return <main className="marketplace marketplace-detail"><nav className="marketplace-nav" aria-label="Navegación del agente"><Link href="/marketplace">← Marketplace</Link><Link href="/constructor">Constructor</Link></nav><p className="marketplace-eyebrow">Creado por {agent.creatorName}</p><h1>{agent.title}</h1><p className="marketplace-description">{agent.description}</p>{agent.forkedFromAgent ? <p className="marketplace-fork">Creado a partir de {agent.forkedFromAgent.title}</p> : null}<section className="marketplace-steps"><h2>Cadena</h2><ol>{agent.steps.map((step, index) => <li key={step.id}><strong>{index + 1}. {step.blockType}</strong><p>{step.instruction}</p>{step.blockType === "leer-documento" ? <label>Documento para este bloque<input type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" disabled={busy} onChange={(event) => document(step.id, event.target.files?.[0] ?? null)} /></label> : null}</li>)}</ol></section><section className="marketplace-run"><h2>Probar agente</h2><textarea value={input} onChange={(event) => setInput(event.target.value)} disabled={busy} placeholder="Escribe un caso de prueba…" /><div className="marketplace-actions"><button onClick={() => void run()} disabled={busy}>{busy ? "Ejecutando…" : "Probar agente"}</button>{own ? <Link href="/constructor">Editar desde Mis agentes</Link> : <button className="marketplace-secondary" onClick={() => void fork()} disabled={busy}>Crear fork</button>}</div>{notice ? <p role="status">{notice}</p> : null}{output ? <article className="marketplace-output"><h2>Respuesta</h2><div>{output}</div>{sources.length ? <section><strong>Fuentes consultadas</strong><ul>{sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a><span>{source.pageAge ?? source.age ?? "Sin fecha verificable"}</span></li>)}</ul></section> : null}</article> : null}</section></main>;
}
